<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<AssetBundlePath></AssetBundlePath>
		<EnableGameDebugging>false</EnableGameDebugging>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Yariazen.PlateUp.ModBuildUtilities" Version="1.13.0" />
	</ItemGroup>
	<ItemGroup>
		<Folder Condition="Exists('Changelogs\Github')" Include="Changelogs\Github" />
	</ItemGroup>
</Project>